import { ArrowRight, CheckCircle2, Cpu, Gauge, ShieldCheck } from 'lucide-react'
import Button from '../components/Button'
import ProductImage from '../components/ProductImage'

export default function About() {
  return (
    <div>
      <section className="border-b border-line"><div className="site-container grid min-h-[540px] items-center gap-12 py-16 lg:grid-cols-2"><div><p className="eyebrow mb-5 text-blue-400">About NOWA</p><h1 className="text-5xl font-extrabold leading-[0.98] tracking-[-0.05em] sm:text-6xl">Hardware chosen with purpose.</h1><p className="mt-7 max-w-xl text-lg leading-8 text-zinc-400">NOWA is a modern technology retailer built for people who care about what goes inside their systems and around their desks.</p><Button to="/shop" className="mt-8">Explore the collection <ArrowRight size={17} /></Button></div><div className="aspect-[4/3] overflow-hidden rounded-xl border border-line bg-panel"><ProductImage src="https://images.unsplash.com/photo-1587202372634-32705e3bf49c?auto=format&fit=crop&w=1400&q=90" alt="Performance computer hardware" className="h-full w-full object-cover opacity-80" /></div></div></section>
      <section className="section-space"><div className="site-container"><div className="mx-auto max-w-3xl text-center"><p className="eyebrow mb-4">Our standard</p><h2 className="text-3xl font-bold tracking-tight sm:text-4xl">Less noise. Better hardware.</h2><p className="mt-5 leading-7 text-zinc-500">We focus on a tighter selection of components and peripherals with a clear reason to exist. Every product is assessed for performance, reliability, and the experience it brings to a complete setup.</p></div><div className="mt-14 grid gap-5 md:grid-cols-3">{[[Gauge, 'Performance first', 'Products selected to deliver meaningful, measurable gains.'], [ShieldCheck, 'Reliable by design', 'Proven hardware from brands builders know and trust.'], [Cpu, 'Technical clarity', 'Useful specifications and direct guidance without the noise.']].map(([Icon, title, text]) => <div key={title} className="rounded-xl border border-line bg-panel p-7"><Icon size={26} className="text-blue-400" strokeWidth={1.5} /><h3 className="mt-6 text-lg font-semibold">{title}</h3><p className="mt-3 text-sm leading-6 text-zinc-500">{text}</p></div>)}</div></div></section>
      <section className="border-y border-line bg-panel"><div className="site-container grid gap-8 py-14 sm:grid-cols-3">{[['16', 'Curated products'], ['8', 'Hardware categories'], ['30 days', 'Simple returns']].map(([value, label]) => <div key={label} className="text-center"><p className="text-3xl font-bold text-white">{value}</p><p className="mt-2 text-sm text-zinc-500">{label}</p></div>)}</div></section>
      <section className="section-space"><div className="site-container flex flex-col items-start justify-between gap-8 rounded-xl border border-line bg-[#101214] p-8 sm:p-12 lg:flex-row lg:items-center"><div><div className="flex items-center gap-2 text-sm text-blue-400"><CheckCircle2 size={17} /> Ready when you are</div><h2 className="mt-3 text-3xl font-bold">Build your next system with confidence.</h2></div><Button to="/shop">Shop hardware <ArrowRight size={17} /></Button></div></section>
    </div>
  )
}
